### ISSUE TITLE
sys-kernel/zenpower-9999 - ocerman github repo is abandoned

### ISSUE THREAD

**Issue by logrusx** [SuperTux88/gentoo-overlay#3]
Hello, it looks like https://github.com/ocerman/zenpower3/ is abandoned, but  it's forked and supported in by Ta180m and https://github.com/Ta180m/zenpower3.git would be the correct EGIT_REPO_URI substitute for now.

Regards,
Georgi

**Comment by SuperTux88** [comment]
Done, I also added an ebuild for the released 0.2.0 version.
