### ISSUE TITLE
dotter package requires sudo as RDEPEND

### ISSUE THREAD

**Issue by DaniD3v** [SuperTux88/gentoo-overlay#5]
When using any { owner=... } type config dotter tries using sudo.

**Comment by SuperTux88** [comment]
That's more of an optional dependency, only for this specific edge case. Most people probably just manage files of their own user in their own home directory, and I don't want to add a hard dependency for everybody to install sudo, if they don't use that feature.

But I added a little note telling people to install sudo themselves if they want to use that feature and sudo isn't installed.
