### ISSUE TITLE
net-misc/warpinator: wants /bin/bwrap and /bin/python3

### ISSUE THREAD

**Issue by ProjectMoon** [SuperTux88/gentoo-overlay#7]
These programs are at `/usr/bin/bwrap` and `/usr/bin/python3` on my system, which of course means warpinator cannot start. After symlinking, warpinator seems to go into an infinite loop of:

```
(warpinator.py:11970): dconf-WARNING **: 10:04:38.643: failed to commit changes to dconf: Could not connect: No such file or directory
```

**Comment by SuperTux88** [comment]
My whole `/bin` is just a symlink to `/usr/bin`, as I use a [merged-usr profile](https://wiki.gentoo.org/wiki/Merge-usr). If warpinator doesn't work in a legacy split-usr profile, I don't know if I can enforce or signal that somehow with the dependencies (I don't think there is a way of depending on profiles). But maybe it fixes your problems if you migrate to a merged-usr profile too? :thinking: 

But maybe it's also just a bug in warpinator, so you can maybe create an upstream bugreport about the wrong paths for `python3` and `bwrap`. There is not much I can do about it, I don't modify paths or anything about warpinator.

There is already an upstream bugreport about your dconf message (https://github.com/linuxmint/warpinator/issues/203), so maybe that helps you with that warning?

As everything works fine for me, I'm not really sure what I can do, as I couldn't even test if any changes I might do would fix something. If you find something that's not an upstream bug but needs to be changed in the ebuild to solve your problems, I'm happy to accept a pull request.

**Comment by ProjectMoon** [comment]
Hmm, I am running OpenRC, but not a split-usr system? I thought the merge-usr thing was only for systemd to move stuff into /usr/bin. All my applications and libraries are in /usr/whatever. The only thing missing is a symlink to /bin. Maybe I will ask about this more on Matrix/IRC and then come back with some more information.

Edit: Also for OpenRC, there don't seem to be such a thing as merged-usr profiles.

**Comment by ProjectMoon** [comment]
So the problem is in this file: https://github.com/linuxmint/warpinator/blob/master/src/warpinator-launch.py

The paths are just hardcoded to `/bin` for some reason. The point of usr-merge on Gentoo is to put things like the python executable under `/usr`, so I think it would make sense to patch this file to change the paths for `bwrap` and `python3` to be `/usr/bin`. This would allow it to work on both OpenRC and systemd systems.

**Comment by SuperTux88** [comment]
If it's a bug upstream it should also be patched in the upstream repo. Like in the first line of this file the path is also `/usr/bin/python3`.

As a workaround for until it's patched upstream, you can just create these 2 symlinks yourself manually, and it should work the same as for me when the whole `/bin` is a symlink to `/usr/bin`. The problem with the dconf warnings is probably unrelated (see the other issue).

**Comment by ProjectMoon** [comment]
I wonder if it has something to do with `bwrap`. Maybe it's supposed to create an isolated environment where python3 is available at `/bin`. I will create an issue upstream and ask about it. Failing that, I will just use portage's patch facility or make a symlink as suggested.

**Comment by ProjectMoon** [comment]
Looks like it's been updated upstream (to another hardcoded path :thinking:), but this means it should work on Gentoo without issue once a new release is made and added to this ebuild repository.

**Comment by SuperTux88** [comment]
Since there wasn't any new release since 2 Months, I now just added the patch to the current version, so I can close this.
